routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::get('/home', 'DashboardController@index');
//
Route::get('/', 'PostController@login')->name('login-post');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');

Route::resource('posts', 'PostController');

// Dashboard views
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/dashboard/old', 'DashboardController@indexOld')->name('dashboardOld');


// Users Controller
Route::get('/user-profile', 'UserController@profile')->name('user-profile');
Route::get('/members', 'UserController@members')->name('members');
Route::get('/email-signature', 'UserController@emailSignature')->name('emailSignature');
Route::post('/user/add-follows', 'UserController@userAddFollows')->name('add-follows');
Route::post('/user/add-connections', 'UserController@userAddConnections')->name('add-connections');
Route::post('/user/upload-profile-photo', 'UserController@uploadProfilePhoto')->name('upload-profile-photo');
Route::post('/user/upload-cover-photo', 'UserController@uploadCoverPhoto')->name('upload-cover-photo');
Route::post('/user/change-password', 'UserController@changePassword')->name('change-password');
Route::post('/user/update-user-profile', 'UserController@updateUserProfile')->name('update-user-profile');


// Profile Comments Controller
Route::post('/user-profile/add-post-like', 'UserController@addPostLike')->name('add-profile-like');
Route::post('/user-profile/comments', 'UserController@comments')->name('add-profile-comments');
Route::post('/user-profile/comment/remove', 'UserController@commentsRemove')->name('remove-profile-comments');


//Events
Route::get('/events', 'EventController@index')->name('events');
Route::post('/events/add-new-event', 'EventController@addNewEvent')->name('add-new-event');
Route::get('/events/edit/{id}', 'EventController@editEvent')->name('edit-event');
Route::post('/events/edit-event', 'EventController@editPostEvent')->name('edit-post-event');
Route::get('/events/list-event', 'EventController@getList')->name('list-event');
Route::get('/events/destroy/{id}', 'EventController@destroy')->name('destroy-event');
Route::get('/events/view/{id}', 'EventController@eventsView')->name('event-view');


// Post Controller
Route::post('/post/add-post-like', 'PostController@addPostLike')->name('add-post-like');
Route::post('/post/comments', 'PostController@comments')->name('add-comments');
Route::post('/post/comment/remove', 'PostController@commentsRemove')->name('remove-comments');


// Poll Controller
Route::get('/poll/create', 'PollController@create')->name('poll-create');
Route::get('/poll/list', 'PollController@getList')->name('poll-list');
Route::get('/poll/edit/{id}', 'PollController@pollEdit')->name('poll-edit');
Route::get('/poll/view/{id}', 'PollController@pollView')->name('poll-view');
Route::post('/poll/edit-post', 'PollController@pollEditPost')->name('poll-edit-post');
Route::post('/poll/add-new-poll', 'PollController@addNewPoll')->name('add-new-poll');
Route::post('/poll/vote', 'PollController@addPollVote')->name('add-poll-vote');
Route::get('/poll/destroy/{id}', 'PollController@destroy')->name('poll-destroy');
Route::get('/poll/results/{poll_id}', 'PollController@viewPollResults')->name('poll-results');
Route::get('/poll/delete-validate/{poll_id}', 'PollController@checkPollHasVote')->name('delete-validate');

// Documentation
Route::get('documentation/list','DocumentationController@listOfDocumentation')->name('documentation-list');


//Announcement
Route::get('announcement/create', 'AnnouncementController@create')->name('announcement-create');
Route::post('announcement/add-new', 'AnnouncementController@addNewAnnouncement')->name('announcement-add-new');
Route::get('announcement/list', 'AnnouncementController@getList')->name('announcement-get-list');
Route::get('announcement/edit/{id}', 'AnnouncementController@editAnnouncement')->name('announcement-edit');
Route::get('announcement/destroy/{id}', 'AnnouncementController@destroy')->name('announcement.destroy');
Route::post('announcement/edit-post', 'AnnouncementController@editPostAnnouncement')->name('announcement-edit-post');

//Setting
Route::get('setting/dashboard', 'SettingController@dashboard')->name('slider-list');
Route::post('setting/dashboard/save', 'SettingController@dashboardSave')->name('setting-dashboard-save');

//Favorite
Route::get('favorite/create', 'FavoriteController@index')->name('favorite-create');
Route::get('favorite/list', 'FavoriteController@favoriteList')->name('favorite-list');
Route::post('favorite/create/post', 'FavoriteController@create')->name('favorite-create-post');
Route::post('favorite/edit/post', 'FavoriteController@editFavorite')->name('favorite-edit-post');
Route::get('favorite/destroy/{id}', 'FavoriteController@destroy')->name('favorite-destroy');
Route::get('favorite/edit/{id}', 'FavoriteController@favoriteEdit')->name('favorite-edit');

Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    echo "cache cleared";die;
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\SettingModel;
use Illuminate\Http\Request;

use App\User;
use Auth;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Session;

class UserController extends Controller
{
    public $setting_model;
    public $user_model;
    public function __construct() 
    {
        $this->middleware(['auth', 'isAdmin']);
        $this->setting_model =  new SettingModel();
        $this->user_model = new User();
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_model = new User();
        $users = $user_model->getUsers();
        return view('users.index')->with('users', $users);
    }

    /**
     * @return mixed
     */
    public function members()
    {
        //get users with paginate
        $user_model = new User();
        $users = $user_model->getUsersByLimit(config('app.pagination_limit_per_page'));

        return view('users.members',[
            'users' => $users
        ]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();
        return view('users.create', ['roles'=>$roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users',
            'password'=>'required|min:6|confirmed'
        ]);

        $user = User::create($request->only('email', 'name', 'password'));

        $roles = $request['roles'];

        if (isset($roles)) {

            foreach ($roles as $role) {
            $role_r = Role::where('id', '=', $role)->firstOrFail();            
            $user->assignRole($role_r);
            }
        }        

        return redirect()->route('users.index')
            ->with('flash_message',
             'User successfully added.');
    }


    public function profile(){


        $user = Auth::user();
        $this->show($user->id);


        return redirect()->action('UserController@show', $user->id);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        // echo "dfdf";die;
        // get user details
        $user_model =  new User();
        $setting_model = new SettingModel();
        $user = $user_model->getUserByID($id);

        // creating activate date ago
        $active_string = $setting_model->timeAgo($user->created_at);

        // get user connection and follows
        $user_connections   = $user_model->getUserConnection($id);
        $user_follows       = $user_model->getUserFollows($id);

        // selected user following status
        $user_following       = $user_model->getUserFollowingByUserID($id);
        $user_connecting       = $user_model->getUserConnectionByUserID($id);

        $countries = $setting_model->getAllCountries();
        $offices = $setting_model->getAllOffices();

        $post_comment = $this->user_model->getCommentsByUserID($id);
        $level_2_post_comment = array();
        foreach ($post_comment  as $post_comment_level)
        {
            $level_2_post_comment[$post_comment_level->user_profile_comment_id] = $this->user_model->getCommentsByUserID($id, $post_comment_level->user_profile_comment_id );
        }


        return view('users.view',[
            'user'                  => $user,
            'activate_ago'          => $active_string,
            'connections'           => $user_connections,
            'follows'               => $user_follows,
            'user_following'        => count($user_following),
            'user_connecting'       => count($user_connecting),
            'countries'             => $countries,
            'offices'               => $offices,
            'post_comment'          => $post_comment,
            'level_2_post_comment'  => $level_2_post_comment,
        ]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::get();

        return view('users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users,email,'.$id,
            'password'=>'required|min:6|confirmed'
        ]);

        $input = $request->only(['name', 'email', 'password']);
        $roles = $request['roles'];
        $user->fill($input)->save();

        if (isset($roles)) {        
            $user->roles()->sync($roles);            
        }        
        else {
            $user->roles()->detach();
        }
        return redirect()->route('users.index')
            ->with('flash_message',
             'User successfully edited.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('users.index')
            ->with('delete_success_message',
             'User successfully deleted.');
    }

    /**
     * Description adda user follow by ajax call
     * @param Request $request
     * @return mixed
     */
    public function userAddFollows(Request $request)
    {
        $user_model = new User();
        $post_data = $request->all();
        $results = $user_model->addUserFollows($post_data);

        $message = "Follow added successfully!";
        $response_code = 200;
        if($results === 0){
            $message = "Follow removed successfully!";
            $response_code = 400;

            // user activity track
            $data = array(
                'user_id'       => Auth::user()->id,
                'type'          => 'Follows',
                'code'          => 'user_follow',
                'description'   => Auth::user()->first_name. " un followed you.",
                'created_at'    => date('Y-m-d H:i:s')
            );
            $this->setting_model->userAction($data);
            // End user activity track

        }else{

            // user activity track
            $data = array(
                'user_id'       => Auth::user()->id,
                'type'          => 'Follows',
                'code'          => 'user_follow',
                'description'   => Auth::user()->first_name. " followed you.",
                'created_at'    => date('Y-m-d H:i:s')
            );
            $this->setting_model->userAction($data);
            // End user activity track

            // notification add
            $description =  Auth::user()->first_name. " followed you.";
            $notification = array(
                'notify_user_id' => $post_data['user_id'],
                'notified_by' => Auth::user()->id,
                'description' => $description,
                'notify_type' => 'follow'
            );
            $this->setting_model->addNotification($notification);
            // notification

        }

        return response()->json([
            'status'         => $results,
            'message'        => $message,
            'response_code'  => $response_code
        ]);

    }

    /**
     * Description adda user connection by ajax call
     * @param Request $request
     * @return mixed
     */
    public function userAddConnections(Request $request)
    {
        $user_model = new User();
        $post_data = $request->all();
        $results = $user_model->addUserConnections($post_data);

        $message = "Connection added successfully!";
        $response_code = 200;
        if($results === 0){
            $message = "Connection removed successfully!";
            $response_code = 400;

            // user activity track
            $data = array(
                'user_id'       => Auth::user()->id,
                'type'          => 'Connection',
                'code'          => 'user_connection',
                'description'   => Auth::user()->first_name. " removed you for the connections",
                'created_at'    => date('Y-m-d H:i:s')
            );
            $this->setting_model->userAction($data);
            // End user activity track

        }else{

            // user activity track
            $data = array(
                'user_id'       => Auth::user()->id,
                'type'          => 'Connection',
                'code'          => 'user_connection',
                'description'   => Auth::user()->first_name. " added you for the connections",
                'created_at'    => date('Y-m-d H:i:s')
            );
            $this->setting_model->userAction($data);
            // End user activity track

            // notification add
            $description =  Auth::user()->first_name. " added you for the connections";

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', '| Add User')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-user-plus'></i> Add User</h1>
    <hr>

    {{-- @include ('errors.list') --}}

    {{ Form::open(array('url' => 'users')) }}

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', '', array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('email', 'Email') }}
        {{ Form::email('email', '', array('class' => 'form-control')) }}
    </div>

    <div class='form-group'>
        @foreach ($roles as $role)
            {{ Form::checkbox('roles[]',  $role->id ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

        @endforeach
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Password') }}<br>
        {{ Form::password('password', array('class' => 'form-control')) }}

    </div>

    <div class="form-group">
        {{ Form::label('password', 'Confirm Password') }}<br>
        {{ Form::password('password_confirmation', array('class' => 'form-control')) }}

    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

</div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit User')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-user-plus'></i> Edit {{$user->name}}</h1>
    <hr>
    {{-- @include ('errors.list') --}}

    {{ Form::model($user, array('route' => array('users.update', $user->id), 'method' => 'PUT')) }} {{-- Form model binding to automatically populate our fields with user data --}}

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('email', 'Email') }}
        {{ Form::email('email', null, array('class' => 'form-control')) }}
    </div>

    <h5><b>Give Role</b></h5>

    <div class='form-group'>
        @foreach ($roles as $role)
            {{ Form::checkbox('roles[]',  $role->id, $user->roles ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

        @endforeach
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Password') }}<br>
        {{ Form::password('password', array('class' => 'form-control')) }}

    </div>

    <div class="form-group">
        {{ Form::label('password', 'Confirm Password') }}<br>
        {{ Form::password('password_confirmation', array('class' => 'form-control')) }}

    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.new_dashboard_app')

@section('title', '| Users')

@section('content')
    <style>
        .pagination li {
            display:inline-block;
            padding:0px;
        }
    </style>

    <!--CONTENT CONTAINER-->
    <!--===================================================-->
    <div id="content-container">

        <!--Page content-->
        <!--===================================================-->
        <div id="page-content">


            <div id="page-head">
                <!--Page Title-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <div style="padding-left:0px;" id="page-title">
                    <h1 style="color:#4d627b;" class="page-header text-overflow">Users</h1>
                </div>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End page title-->

                <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol style="padding-left:0px;" class="breadcrumb">
                    <li><a href="#"><i style="color:#4d627b;" class="demo-pli-home"></i></a></li>
                    <li><a style="color:#4d627b;" href="#">Users</a></li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->
            </div>

            <div id="users">
                <div class="filter-group row">

                    <!-- Contact Toolbar -->
                    <!---------------------------------->
                    <div style="margin-top: 20px;" class=" pad-btm">
                        <div class="col-sm-6 toolbar-left">
                            @can('Role View')<a href="{{ route('roles.index') }}" id="demo-btn-addrow" class="btn btn-purple">Roles</a>@endcan
                            @can('Permission View')<a href="{{ route('permissions.index') }}" id="demo-btn-addrow" class="btn btn-purple">Permissions</a>@endcan
                        <!--@can('User Create')<a href="{{ route('users.create') }}" id="demo-btn-addrow" class="btn btn-purple">Add User</a>@endcan -->
                        </div>
                        <div class="col-sm-6 toolbar-right">
                            <form class="form-inline">
                                <div class="form-group">
                                    <input type="text" class="search form-control" placeholder="Search" />
                                </div>

                            </form>
                        </div>
                    </div>
                    <!---------------------------------->
                        </div>

                        <div id="content"  class="list row demo">
                            @php
                            $id = 0;
                            @endphp
                            @foreach ($users as $user)
                                @php
                                $id++;
                                @endphp
                                <!-- Contact Widget -->
                                <div  class="col-sm-3 col-md-3 col-xs-6 list--list-item">
                                    <div class="panel pos-rel">
                                        <div class="pad-all text-center">
                                            <div class="widget-control">
                                                <div class="btn-group dropdown">
                                                    <a href="#" class="dropdown-toggle btn btn-trans" data-toggle="dropdown" aria-expanded="false"><i class="demo-psi-dot-vertical icon-lg"></i></a>
                                                    <ul class="dropdown-menu dropdown-menu-right">
                                                        @if(auth()->user()->can('User Edit'))
                                                            @can('User Edit')
                                                            <li><a href="{{ route('users.edit', $user->id) }}"><i class="icon-lg icon-fw demo-psi-pen-5"></i> Edit</a></li>
                                                            @endcan
                                                            @endif

                                                            @if(auth()->user()->can('User Delete'))
                                                            @can('User Delete')
                                                                    <!--{!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id], 'id' => 'form-user-'.$user->id, 'class' => 'delete-form' ]) !!}
                                                                    <button type="button" data-form="form-user-{{ $user->id }}" class="btn delete-btn"><i class="icon-lg icon-fw demo-pli-recycling"></i> Delete</button>
                                                            {!! Form::close() !!}-->
                                                            <li><a href="{{ route('users.edit', $user->id) }}"><i class="icon-lg icon-fw demo-pli-recycling"></i> Remove</a></li>
                                                            @endcan
                                                        @endif
                                                    </ul>
                                                </div>
                                            </div>
                                            <a>
                                                <img alt="Profile Picture" class="img-lg img-circle mar-btm" src="{{ asset($user->profile_image) }}">
                                                <p class="text-lg text-semibold mar-no text-main name">{{ $user->name }}</p>
                                                <p class="text-sm profession">{{ $user->profession }}</p>
                                                <p class="text-sm country">{{ $user->country_name }}</p>

                                                @if(auth()->user()->can('User View'))
                                                    @can('User View')
                                                    <a href="{{ route('users.show', $user->id) }}" class="btn btn-primary mar-ver"><i class="demo-pli-male icon-fw"></i>View Profile</a>
                                                    @endcan
                                                @endif

                                                <ul class="list-unstyled text-center bord-top pad-top mar-no row">
                                                    <li class="col-xs-6">
                                                        <span class="text-lg text-semibold text-main">{{ $user->user_follows }}</span>
                                                        <p class="text-muted mar-no">Following</p>
                                                    </li>
                                                    <li class="col-xs-6">
                                                        <span class="text-lg text-semibold text-main">{{ $user->user_connetions }}</span>
                                                        <p class="text-muted mar-no">Connection</p>
                                                    </li>
                                                </ul>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                        <ul id="page-selection" class="pagination demo"></ul>
                        <!--<div class="no-result">No Results</div>-->
                    </div>
                </div>
            </div>
            <!--===================================================-->
            <!--End page content-->
        </div>
        <!--===================================================-->
        <!--END CONTENT CONTAINER-->

        @endsection

        @section('page-js')
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

            <script>
                var options = {
                    valueNames: [
                        'name',
                            'profession','country',
                        { data: ['gender']}
                    ],
                    page: 8,
                    pagination: true
                };
                var userList = new List('users', options);

                function resetList(){
                    userList.search();
                    userList.filter();
                    userList.update();
                    $(".filter-all").prop('checked', true);
                    $('.filter').prop('checked', false);
                    $('.search').val('');
                    //console.log('Reset Successfully!');
                };

                function updateList(){
                    var values_gender = $("input[name=gender]:checked").val();
                    var values_address = $("input[name=address]:checked").val();
                    console.log(values_gender, values_address);

                    userList.filter(function (item) {
                        var genderFilter = false;
                        var addressFilter = false;

                        if(values_gender == "all")
                        {
                            genderFilter = true;
                        } else {
                            genderFilter = item.values().gender == values_gender;

                        }
                        if(values_address == null)
                        {
                            addressFilter = true;
                        } else {
                            addressFilter = item.values().address.indexOf(values_address) >= 0;
                        }
                        return addressFilter && genderFilter
                    });
                    userList.update();
                    //console.log('Filtered: ' + values_gender);
                }
            </script>

            <!-- PAGE RELATED PLUGIN(S) -->
            <script src="{{ asset('asset/js/plugin/datatables/jquery.dataTables.min.js') }}"></script>
            <script src="{{ asset('asset/js/plugin/datatables/dataTables.colVis.min.js') }}"></script>
            <script src="{{ asset('asset/js/plugin/datatables/dataTables.tableTools.min.js') }}"></script>
            <script src="{{ asset('asset/js/plugin/datatables/dataTables.bootstrap.min.js') }}"></script>
            <script src="{{ asset('asset/js/plugin/datatable-responsive/datatables.responsive.min.js') }}"></script>

            <script>
                // DO NOT REMOVE : GLOBAL FUNCTIONS!
                $(document).ready(function() {
                    pageSetUp();

                    /* // DOM Position key index //
                     l - Length changing (dropdown)
                     f - Filtering input (search)
                     t - The Table! (datatable)
                     i - Information (records)
                     p - Pagination (paging)
                     r - pRocessing
                     < and > - div elements
                     <"#id" and > - div with an id
                     <"class" and > - div with a class
                     <"#id.class" and > - div with an id and class
                     Also see: http://legacy.datatables.net/usage/features
                     */

                    /* BASIC ;*/
                    var responsiveHelper_dt_basic = undefined;

                    var breakpointDefinition = {
                        tablet: 1024,
                        phone: 480
                    };

                    $('#dt_basic').dataTable({
                        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                        "t" +
                        "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                        "autoWidth": true,
                        "oLanguage": {
                            "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                        },
                        "preDrawCallback": function () {
                            // Initialize the responsive datatables helper once.
                            if (!responsiveHelper_dt_basic) {
                                responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                            }
                        },
                        "rowCallback": function (nRow) {
                            responsiveHelper_dt_basic.createExpandIcon(nRow);
                        },
                        "drawCallback": function (oSettings) {
                            responsiveHelper_dt_basic.respond();
                        }
                    });
                });
            </script>
@endsection